export const contributors = [
  {
    name: 'Joel Chávez',
    xs: 12,
    sm: 6,
    md: 3,
    role: 'Programmer',
    description: 'Computer Science student at ITESM Monterrey',
    avatar: 'https://avatars.githubusercontent.com/u/43424834?v=4',
    github: 'jchv99',
  },
  {
    name: 'Rodrigo Kwok',
    xs: 12,
    sm: 6,
    md: 3,
    role: 'Programmer',
    description: 'Computer Science student at ITESM Monterrey',
    avatar: 'https://avatars.githubusercontent.com/u/43385076?v=4',
    github: 'RodrigoRK7',
  },
  {
    name: 'Daniel David',
    xs: 12,
    sm: 6,
    md: 3,
    role: 'Programmer',
    description: 'Computer Science student at ITESM Monterrey',
    avatar: 'https://avatars.githubusercontent.com/u/54334789?v=4',
    github: 'Danyboyyy',
  },
  {
    name: 'Omar Balboa',
    xs: 12,
    sm: 6,
    md: 3,
    role: 'Programmer',
    description: 'Computer Science student at ITESM Monterrey',
    github: 'OmarBalboa',
    avatar: 'https://avatars.githubusercontent.com/u/43385028?v=4',
  },
  {
    name: 'Alex Vargas',
    xs: 12,
    sm: 6,
    md: 4,
    role: 'Programmer',
    description: 'Computer Science student at ITESM Monterrey',
    avatar: 'https://avatars.githubusercontent.com/u/43385032?v=4',
    github: 'alexvargas01',
  },
  {
    name: 'Patricio Güereque',
    xs: 12,
    sm: 6,
    md: 4,
    role: 'Project Lead',
    description:
      'Fullstack developer and Computer Science undergrad ad ITESM Monterrey',
    avatar: 'https://avatars.githubusercontent.com/u/19732552?v=4',
    twitter: 'patoguereque',
    github: 'patoguereque',
    mail: 'contacto@patoguereque.com',
  },
  {
    name: 'Cesar Martínez',
    xs: 12,
    sm: 12,
    md: 4,
    role: 'Programmer',
    description: 'Computer Science student at ITESM Monterrey',
    avatar: 'https://avatars.githubusercontent.com/u/42587773?v=4',
    github: 'CesarMtzV',
  },
];
